pipeline {
    registry 'http://dr.sqilab.com:25000/'
    agent none
    stages {
        stage('Build image'){
            steps{
                script{
                    docker.build registry+'jmungai/flask-example:$BUILD_NUMBER'
                }
            }
        }
        stage('Test'){
            steps {
                sh 'echo "Testing application"'
            }
        }
        stage('Deploy'){
            steps{
                timeout(time: 3,unit:'MINUTES'){
                    sh 'echo "Welcome to failed pipeline"'
                }
            }
        }
    }
    post {
        always{
            echo 'Clean up build'
        }
        success {
            echo 'Successful build'
        }
        failure{
            echo 'Build failed'
        }
    }
}